"""Map Four Seasons URL path slugs to SERP region (ISO 3166-1 alpha-2)."""

from __future__ import annotations

from urllib.parse import urlparse

DEFAULT_REGION = "US"
DEFAULT_LANGUAGE = "en"
DEFAULT_DEVICE = "mobile"

# Slug = first path segment on www.fourseasons.com/{slug}/...
REGION_BY_SLUG: dict[str, str] = {
    "abudhabi": "AE",
    "alexandria": "EG",
    "amaalaredsea": "SA",
    "amman": "JO",
    "anguilla": "AI",
    "athens": "GR",
    "atlanta": "US",
    "austin": "US",
    "bahrain": "BH",
    "baku": "AZ",
    "baltimore": "US",
    "bangkok": "TH",
    "beijing": "CN",
    "bengaluru": "IN",
    "beverlywilshire": "US",
    "bogota": "CO",
    "borabora": "PF",
    "bosphorus": "TR",
    "boston": "US",
    "budapest": "HU",
    "buenosaires": "AR",
    "cabodelsol": "MX",
    "cairofr": "EG",
    "caironp": "EG",
    "capferrat": "FR",
    "cartagena": "CO",
    "casablanca": "MA",
    "chiangmai": "TH",
    "chicago": "US",
    "costarica": "CR",
    "denver": "US",
    "doha": "QA",
    "dubaidifc": "AE",
    "dubaijb": "AE",
    "embarcadero": "US",
    "explorerpalau": "PW",
    "florence": "IT",
    "fortlauderdale": "US",
    "geneva": "CH",
    "goldentriangle": "TH",
    "guangzhou": "CN",
    "hampshire": "GB",
    "hangzhou": "CN",
    "hangzhoucentre": "CN",
    "hoian": "VN",
    "hongkong": "HK",
    "houston": "US",
    "hualalai": "US",
    "istanbul": "TR",
    "jacksonhole": "US",
    "jakarta": "ID",
    "jimbaranbay": "ID",
    "johannesburg": "ZA",
    "kohsamui": "TH",
    "kualalumpur": "MY",
    "kuwait": "KW",
    "kyoto": "JP",
    "lanai": "US",
    "langkawi": "MY",
    "lasvegas": "US",
    "lisbon": "PT",
    "london": "GB",
    "losangeles": "US",
    "loscabos": "MX",
    "macau": "MO",
    "madrid": "ES",
    "maldiveskh": "MV",
    "maldiveslg": "MV",
    "mallorca": "ES",
    "marrakech": "MA",
    "maui": "US",
    "mauritius": "MU",
    "megeve": "FR",
    "mexico": "MX",
    "miami": "US",
    "milan": "IT",
    "minneapolis": "US",
    "montreal": "CA",
    "mumbai": "IN",
    "mykonos": "GR",
    "napavalley": "US",
    "naplesbeachclub": "US",
    "nashville": "US",
    "naviva": "MX",
    "nevis": "KN",
    "neworleans": "US",
    "newyork": "US",
    "newyorkdowntown": "US",
    "northsandiego": "US",
    "oahu": "US",
    "oceanclub": "BS",
    "onedalton": "US",
    "orlando": "US",
    "osaka": "JP",
    "otemachi": "JP",
    "palmbeach": "US",
    "paris": "FR",
    "philadelphia": "US",
    "prague": "CZ",
    "puertorico": "US",
    "puntamita": "MX",
    "rabat": "MA",
    "redseashuraisland": "SA",
    "riyadh": "SA",
    "sanfrancisco": "US",
    "santafe": "US",
    "sayan": "ID",
    "scottsdale": "US",
    "seattle": "US",
    "seoul": "KR",
    "serengeti": "TZ",
    "seychelles": "SC",
    "seychellesdesroches": "SC",
    "sharmelsheikh": "EG",
    "shenzhen": "CN",
    "siliconvalley": "US",
    "singapore": "SG",
    "stlouis": "US",
    "surfside": "US",
    "suzhou": "CN",
    "sydney": "AU",
    "tamarindo": "CR",
    "taormina": "IT",
    "thepearlqatar": "QA",
    "tokyo": "JP",
    "toronto": "CA",
    "towerbridge": "GB",
    "tunis": "TN",
    "vail": "US",
    "washington": "US",
    "westlakevillage": "US",
    "whistler": "CA",
}


def url_slug(url: str) -> str:
    parts = [segment for segment in urlparse(url).path.split("/") if segment]
    return parts[0].lower() if parts else ""


def region_for_url(url: str) -> str:
    slug = url_slug(url)
    return REGION_BY_SLUG.get(slug, DEFAULT_REGION)
